export const hotelTypes = [
    "Luxury",
    "Boutique",
    "Full-Service",
    "Limited-Service",
    "Resort",
    "Airport",
    "City Center",
    "Suburban",
    "Beach",
    "Mountain or Ski",
    "Island",
    "Business",
    "Family",
    "Couples/Adult-Only",
    "Adventure",
    "Eco-Friendly",
    "Hostels",
    "Capsule",
    "Extended-Stay",
    "Heritage or Historic",
    "Floating",
    "Treehouse",
    "Motel",
    "Cabin",
    "Golf Resort",
]

export const hotelFacilities = [
    "24-hour front desk",
    "Room service",
    "Swimming pool",
    "Fitness center",
    "Wellness center",
    "Restaurant",
    "Bar/lounge",
    "Business center",
    "Conference rooms",
    "Wi-Fi",
    "Parking space",
    "Laundry services",
    "Supermarket",
    "Forex bureau",
    "ATM/cash machine",
    "Babysitting services",
    "Children's play area",
    "Pet-friendly services",
    "Air conditioning",
    "Heating",
    "Coffee/tea maker",
    "Hairdryer",
    "Iron and ironing board",
    "Flat-screen TV",
    "Cable/satellite channels",
    "Kitchenette",
    "Balcony or terrace",
    "Garden",
    "Beach access",
    "Tennis courts",
    "Golf course",
    "Bicycle rentals",
    "Hiking trails",
    "Private beach area",
    "On-site casino",
    "Evening entertainment",
    "Library",
    "Lounge area",
    "Massage services",
]